Teste_Clinica/Teste_Clinica/Models/Clientes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Teste_Clinica.Models
{
    public class Clientes
    {
        [Display(Name="Id do Cliente")]
        public int IdCliente { get; set; }

        [Required(ErrorMessage = "Campo não pode ficar em branco")]
        [StringLength(50, ErrorMessage ="O Nome não pode ter mais de 50 caracteres")]
        public string Nome { get; set; }
        
        [Required(ErrorMessage = "Campo não pode ficar em branco")]
        [StringLength(15, ErrorMessage = "O CPF não pode ter mais de 15 caracteres")]
        public string Cpf { get; set; }

        [Required(ErrorMessage = "Campo não pode ficar em branco")]
        [StringLength(60, ErrorMessage = "O Endereço não pode ter mais de 60 caracteres")]
        public string Endereco { get; set; }

        [Required(ErrorMessage = "Campo não pode ficar em branco")]
        [StringLength(20, ErrorMessage = "O Telefone não pode ter mais de 20 caracteres")]
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Campo não pode ficar em branco")]
        [StringLength(50, ErrorMessage = "O Email não pode ter mais de 50 caracteres")]
        [RegularExpression(@"^[a-zA-Z]+(([\'\,\.\- ][a-zA-Z ])?[a-zA-Z]*)*\s+<(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})>$|^(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})$", ErrorMessage = "Formato do E-mail Inválido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo não pode ficar em branco")]
        [StringLength(10, ErrorMessage = "O Sexo não pode ter mais de 10 caracteres")]
        public string Sexo { get; set; }

        //public List<SelectListItem> ListaSexo = new List<SelectListItem>();

        //public List<SelectListItem> GerarListaSexo()
        //{
        //    ListaSexo.Add(new SelectListItem { Text = "Feminino", Value = "Feminino", Selected = true });
        //    ListaSexo.Add(new SelectListItem { Text = "Masculino", Value = "Masculino" });
        //    return ListaSexo;
        //}


    }
}

Teste_Clinica/Teste_Clinica/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Teste_Clinica.Models;
using Teste_Clinica.Models.BD;

namespace Teste_Clinica.Controllers
{
    public class ClientesController : Controller
    {
        Login login = new Login();

        Clientes cliente = new Clientes();
        // GET: Clientes
        public ActionResult Consulta()
        {
            if (login.GetUsuarioLogado() == "")
            {
                return RedirectToAction("Login", "Home").Mensagem("Faça o login antes de acessar o sistema!", "Usuário não encontrado");
            }
            ClienteBD clienteBD = new ClienteBD();
            
            return View(clienteBD.ListaClientes());
        }

        public ActionResult Cadastrar()
        {
            if (login.GetUsuarioLogado() == "")
            {
                return RedirectToAction("Login", "Home").Mensagem("Faça o login antes de acessar o sistema!", "Usuário não encontrado");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(Clientes clientedigitado)
        {
            if (ModelState.IsValid)
            {
                ClienteBD clienteBD = new ClienteBD();
                clienteBD.Cadastrar(clientedigitado);
                if (clienteBD.mensagem == "")
                {
                    return RedirectToAction("Consulta", "Clientes").Mensagem("Cliente cadastrado com sucesso!", "Cadastro realizado");
                }
                else
                {
                    return View(clientedigitado).Mensagem(clienteBD.mensagem);
                }
            }
            return View(clientedigitado);
        }

        public ActionResult Detalhes(int id)
        {
            if (login.GetUsuarioLogado() == "")
            {
                return RedirectToAction("Login", "Home").Mensagem("Faça o login antes de acessar o sistema!", "Usuário não encontrado");
            }
            ClienteBD clienteBD = new ClienteBD();

            return View(clienteBD.Buscar(id));
        }

        public ActionResult Excluir(int id)
        {
            if (login.GetUsuarioLogado() == "")
            {
                return RedirectToAction("Login", "Home").Mensagem("Faça o login antes de acessar o sistema!", "Usuário não encontrado");
            }
            ClienteBD clienteBD = new ClienteBD();

            return View(clienteBD.Buscar(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Excluir(Clientes cliente)
        {
            ClienteBD clienteBD = new ClienteBD();
            clienteBD.Excluir(cliente.IdCliente);
            if (clienteBD.mensagem == "")
            {
                return RedirectToAction("Consulta", "Clientes").Mensagem("Cliente excluído com sucesso!", "Cliente excluído");
            }

            return View(cliente).Mensagem("Erro ao excluir!" + clienteBD.mensagem, "Erro");
        }

        public ActionResult Editar(int id)
        {
            if (login.GetUsuarioLogado() == "")
            {
                return RedirectToAction("Login", "Home").Mensagem("Faça o login antes de acessar o sistema!", "Usuário não encontrado");
            }
            ClienteBD clienteBD = new ClienteBD();

            return View(clienteBD.Buscar(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Clientes cliente)
        {
            ClienteBD clienteBD = new ClienteBD();
            clienteBD.Editar(cliente);
            if (clienteBD.mensagem == "")
            {
                return RedirectToAction("Consulta", "Clientes").Mensagem("Cliente alterado com sucesso!", "Cliente alterado");
            }

            return View(cliente).Mensagem("Erro ao alterar!" + clienteBD.mensagem, "Erro");
        }
    }
}

Teste_Clinica/Teste_Clinica/Controllers/SistemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Teste_Clinica.Models;

namespace Teste_Clinica.Controllers
{
    public class SistemaController : Controller
    {
        Login usuario = new Login();

        // GET: Sistema
        public ActionResult Index()
        {
            if (usuario.GetUsuarioLogado() == "")
            {
                return RedirectToAction("Login", "Home").Mensagem("Faça o login antes de acessar o sistema!", "Usuário não encontrado");
            }

            ViewBag.Usuario = usuario.GetUsuarioLogado();
            return View();
        }
    }
}

Teste_Clinica/Teste_Clinica/Views/Clientes/Cadastrar.cshtml
@model Teste_Clinica.Models.Clientes

@{
    ViewBag.Title = "Cadastrar Cliente";
}

<h2>Cadastrar Cliente</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="btn btn-default">
    @Html.ActionLink("Cancelar e voltar à consulta", "Consulta")
</div>

<div class="btn btn-default">
    @Html.ActionLink("Voltar à página principal", "Index", "Sistema")
</div>

Teste_Clinica/Teste_Clinica/Views/Clientes/Consulta.cshtml
@model IEnumerable<Teste_Clinica.Models.Clientes>

@{
    ViewBag.Title = "Consulta";
}

<h2>Consulta de Clientes</h2>

<p class="btn btn-default">
    @Html.ActionLink("Cadastrar novo cliente", "Cadastrar")
</p>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id = item.IdCliente }) |
            @Html.ActionLink("Ver detalhes", "Detalhes", new { id = item.IdCliente }) |
            @Html.ActionLink("Excluir", "Excluir", new { id = item.IdCliente })
        </td>
    </tr>
}

</table>

Teste_Clinica/Teste_Clinica/Views/Clientes/Detalhes.cshtml
@model Teste_Clinica.Models.Clientes

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes do cliente</h2>
<br />
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

    </dl>
</div>
<div class="btn btn-sm btn-default">
    @Html.ActionLink("Editar", "Editar", new { /* id = Model.PrimaryKey */ }) 
</div>
<br />
<br />

<div class="btn btn-default">
    @Html.ActionLink("Voltar à consulta", "Consulta")
</div>

<div class="btn btn-default">
    @Html.ActionLink("Voltar à página principal", "Index", "Sistema")
</div>

Teste_Clinica/Teste_Clinica/Views/Clientes/Editar.cshtml
@model Teste_Clinica.Models.Clientes

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Cliente</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.IdCliente)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar alterações" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="btn btn-default">
    @Html.ActionLink("Cancelar", "Consulta", "Clientes")
</div>

Teste_Clinica/Teste_Clinica/Views/Clientes/Excluir.cshtml
@model Teste_Clinica.Models.Clientes

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir Cliente</h2>

<h3>Tem certeza de que você deseja excluir este cliente?</h3>
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.IdCliente) @* Para registrar o id e enviar para o controller *@

        <div class="form-actions pull-left">
            <input type="submit" value="Excluir" class="btn btn-danger" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; @*espaços em branco*@
        </div>
            <div class="btn btn-default">
                @Html.ActionLink("Cancelar", "Consulta", "Clientes")
            </div>
    }
</div>